
// This file has been generated by the GUI designer. Do not modify.
namespace RLToolkit.Widgets
{
	public partial class GridSelector
	{
		private global::Gtk.Table tableRoot;
		private global::Gtk.HBox horizontalControl;
		private global::Gtk.Label lblHEmpty1;
		private global::Gtk.Button btnHMinus;
		private global::Gtk.Image imgHMinus;
		private global::Gtk.Button btnHPlus;
		private global::Gtk.Image imgHPlus;
		private global::Gtk.Label lblHEmpty2;
		private global::Gtk.Label lblCEmpty;
		private global::Gtk.Table tableContent;
		private global::Gtk.VBox verticalControl;
		private global::Gtk.Label lblVEmpty1;
		private global::Gtk.Button btnVMinus;
		private global::Gtk.Image imgVMinus;
		private global::Gtk.Button btnVPlus;
		private global::Gtk.Image imgVPlus;
		private global::Gtk.Label lblVEmpty2;

        /// <summary>
        /// Build this instance.
        /// </summary>
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RLToolkit.Widgets.GridSelector
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RLToolkit.Widgets.GridSelector";
			// Container child RLToolkit.Widgets.GridSelector.Gtk.Container+ContainerChild
			this.tableRoot = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.tableRoot.Name = "tableRoot";
			this.tableRoot.RowSpacing = ((uint)(6));
			this.tableRoot.ColumnSpacing = ((uint)(6));
			// Container child tableRoot.Gtk.Table+TableChild
			this.horizontalControl = new global::Gtk.HBox ();
			this.horizontalControl.Name = "horizontalControl";
			this.horizontalControl.Spacing = 6;
			// Container child horizontalControl.Gtk.Box+BoxChild
			this.lblHEmpty1 = new global::Gtk.Label ();
			this.lblHEmpty1.Name = "lblHEmpty1";
			this.horizontalControl.Add (this.lblHEmpty1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.horizontalControl [this.lblHEmpty1]));
			w1.Position = 0;
			// Container child horizontalControl.Gtk.Box+BoxChild
			this.btnHMinus = new global::Gtk.Button ();
			this.btnHMinus.WidthRequest = 30;
			this.btnHMinus.HeightRequest = 30;
			this.btnHMinus.CanFocus = true;
			this.btnHMinus.Name = "btnHMinus";
			// Container child btnHMinus.Gtk.Container+ContainerChild
			this.imgHMinus = new global::Gtk.Image ();
			this.imgHMinus.Name = "imgHMinus";
			this.imgHMinus.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			this.btnHMinus.Add (this.imgHMinus);
			this.btnHMinus.Label = null;
			this.horizontalControl.Add (this.btnHMinus);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.horizontalControl [this.btnHMinus]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child horizontalControl.Gtk.Box+BoxChild
			this.btnHPlus = new global::Gtk.Button ();
			this.btnHPlus.WidthRequest = 30;
			this.btnHPlus.HeightRequest = 30;
			this.btnHPlus.CanFocus = true;
			this.btnHPlus.Name = "btnHPlus";
			// Container child btnHPlus.Gtk.Container+ContainerChild
			this.imgHPlus = new global::Gtk.Image ();
			this.imgHPlus.Name = "imgHPlus";
			this.imgHPlus.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.btnHPlus.Add (this.imgHPlus);
			this.btnHPlus.Label = null;
			this.horizontalControl.Add (this.btnHPlus);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.horizontalControl [this.btnHPlus]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child horizontalControl.Gtk.Box+BoxChild
			this.lblHEmpty2 = new global::Gtk.Label ();
			this.lblHEmpty2.Name = "lblHEmpty2";
			this.horizontalControl.Add (this.lblHEmpty2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.horizontalControl [this.lblHEmpty2]));
			w6.Position = 3;
			this.tableRoot.Add (this.horizontalControl);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tableRoot [this.horizontalControl]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRoot.Gtk.Table+TableChild
			this.lblCEmpty = new global::Gtk.Label ();
			this.lblCEmpty.Name = "lblCEmpty";
			this.tableRoot.Add (this.lblCEmpty);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tableRoot [this.lblCEmpty]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRoot.Gtk.Table+TableChild
			this.tableContent = new global::Gtk.Table (((uint)(2)), ((uint)(2)), true);
			this.tableContent.Name = "tableContent";
			this.tableContent.RowSpacing = ((uint)(6));
			this.tableContent.ColumnSpacing = ((uint)(6));
			this.tableContent.BorderWidth = ((uint)(3));
			this.tableRoot.Add (this.tableContent);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableRoot [this.tableContent]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRoot.Gtk.Table+TableChild
			this.verticalControl = new global::Gtk.VBox ();
			this.verticalControl.Name = "verticalControl";
			this.verticalControl.Spacing = 6;
			// Container child verticalControl.Gtk.Box+BoxChild
			this.lblVEmpty1 = new global::Gtk.Label ();
			this.lblVEmpty1.Name = "lblVEmpty1";
			this.verticalControl.Add (this.lblVEmpty1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.verticalControl [this.lblVEmpty1]));
			w10.Position = 0;
			// Container child verticalControl.Gtk.Box+BoxChild
			this.btnVMinus = new global::Gtk.Button ();
			this.btnVMinus.WidthRequest = 30;
			this.btnVMinus.HeightRequest = 30;
			this.btnVMinus.CanFocus = true;
			this.btnVMinus.Name = "btnVMinus";
			// Container child btnVMinus.Gtk.Container+ContainerChild
			this.imgVMinus = new global::Gtk.Image ();
			this.imgVMinus.Name = "imgVMinus";
			this.imgVMinus.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			this.btnVMinus.Add (this.imgVMinus);
			this.btnVMinus.Label = null;
			this.verticalControl.Add (this.btnVMinus);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.verticalControl [this.btnVMinus]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child verticalControl.Gtk.Box+BoxChild
			this.btnVPlus = new global::Gtk.Button ();
			this.btnVPlus.WidthRequest = 30;
			this.btnVPlus.HeightRequest = 30;
			this.btnVPlus.CanFocus = true;
			this.btnVPlus.Name = "btnVPlus";
			// Container child btnVPlus.Gtk.Container+ContainerChild
			this.imgVPlus = new global::Gtk.Image ();
			this.imgVPlus.Name = "imgVPlus";
			this.imgVPlus.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			this.btnVPlus.Add (this.imgVPlus);
			this.btnVPlus.Label = null;
			this.verticalControl.Add (this.btnVPlus);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.verticalControl [this.btnVPlus]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child verticalControl.Gtk.Box+BoxChild
			this.lblVEmpty2 = new global::Gtk.Label ();
			this.lblVEmpty2.Name = "lblVEmpty2";
			this.verticalControl.Add (this.lblVEmpty2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.verticalControl [this.lblVEmpty2]));
			w15.Position = 3;
			this.tableRoot.Add (this.verticalControl);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableRoot [this.verticalControl]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.tableRoot);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnVMinus.Clicked += new global::System.EventHandler (this.OnBtnVMinusClicked);
			this.btnVPlus.Clicked += new global::System.EventHandler (this.OnBtnVPlusClicked);
			this.btnHMinus.Clicked += new global::System.EventHandler (this.OnBtnHMinusClicked);
			this.btnHPlus.Clicked += new global::System.EventHandler (this.OnBtnHPlusClicked);
		}
	}
}
