
// This file has been generated by the GUI designer. Do not modify.
namespace RLToolkit.Widgets
{
	public partial class DynamicRow
	{
		private global::Gtk.VBox handler;
		private global::Gtk.VBox rowBox;
		private global::Gtk.HBox rowHandler;
		private global::Gtk.Label labelEmpty1;
		private global::Gtk.Button btnMinus;
		private global::Gtk.Button btnPlus;
		private global::Gtk.Label labelEmpty2;

        /// <summary>
        /// Build this instance.
        /// </summary>
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RLToolkit.Widgets.DynamicRow
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RLToolkit.Widgets.DynamicRow";
			// Container child RLToolkit.Widgets.DynamicRow.Gtk.Container+ContainerChild
			this.handler = new global::Gtk.VBox ();
			this.handler.Name = "handler";
			this.handler.Spacing = 6;
			// Container child handler.Gtk.Box+BoxChild
			this.rowBox = new global::Gtk.VBox ();
			this.rowBox.Name = "rowBox";
			this.rowBox.Spacing = 6;
			this.handler.Add (this.rowBox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.handler [this.rowBox]));
			w1.Position = 0;
			// Container child handler.Gtk.Box+BoxChild
			this.rowHandler = new global::Gtk.HBox ();
			this.rowHandler.Name = "rowHandler";
			this.rowHandler.Spacing = 6;
			// Container child rowHandler.Gtk.Box+BoxChild
			this.labelEmpty1 = new global::Gtk.Label ();
			this.labelEmpty1.WidthRequest = 30;
			this.labelEmpty1.Name = "labelEmpty1";
			this.rowHandler.Add (this.labelEmpty1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.rowHandler [this.labelEmpty1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child rowHandler.Gtk.Box+BoxChild
			this.btnMinus = new global::Gtk.Button ();
			this.btnMinus.WidthRequest = 22;
			this.btnMinus.CanFocus = true;
			this.btnMinus.Name = "btnMinus";
			this.btnMinus.UseUnderline = true;
			this.btnMinus.Label = global::Mono.Unix.Catalog.GetString ("-");
			this.rowHandler.Add (this.btnMinus);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.rowHandler [this.btnMinus]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child rowHandler.Gtk.Box+BoxChild
			this.btnPlus = new global::Gtk.Button ();
			this.btnPlus.WidthRequest = 22;
			this.btnPlus.CanFocus = true;
			this.btnPlus.Name = "btnPlus";
			this.btnPlus.UseUnderline = true;
			this.btnPlus.Label = global::Mono.Unix.Catalog.GetString ("+");
			this.rowHandler.Add (this.btnPlus);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.rowHandler [this.btnPlus]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child rowHandler.Gtk.Box+BoxChild
			this.labelEmpty2 = new global::Gtk.Label ();
			this.labelEmpty2.Name = "labelEmpty2";
			this.rowHandler.Add (this.labelEmpty2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.rowHandler [this.labelEmpty2]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 3;
			this.handler.Add (this.rowHandler);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.handler [this.rowHandler]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.handler);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnMinus.Clicked += new global::System.EventHandler (this.OnBtnMinusClicked);
			this.btnPlus.Clicked += new global::System.EventHandler (this.OnBtnPlusClicked);
		}
	}
}
