
// This file has been generated by the GUI designer. Do not modify.
namespace RLToolkit.Widgets
{
	public partial class DynamicColumn
	{
		private global::Gtk.HBox columnController;
		private global::Gtk.HBox columnBox;
		private global::Gtk.VBox minuxControl;
		private global::Gtk.Label labelEmpty1;
		private global::Gtk.Button btnMinus;
		private global::Gtk.Label labelEmpty2;
		private global::Gtk.VBox plusControl;
		private global::Gtk.Label labelEmpty3;
		private global::Gtk.Button btnPlus;
		private global::Gtk.Label labelEmpty4;

        /// <summary>
        /// Build this instance.
        /// </summary>
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RLToolkit.Widgets.DynamicColumn
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RLToolkit.Widgets.DynamicColumn";
			// Container child RLToolkit.Widgets.DynamicColumn.Gtk.Container+ContainerChild
			this.columnController = new global::Gtk.HBox ();
			this.columnController.Name = "columnController";
			this.columnController.Spacing = 6;
			// Container child columnController.Gtk.Box+BoxChild
			this.columnBox = new global::Gtk.HBox ();
			this.columnBox.Name = "columnBox";
			this.columnBox.Spacing = 6;
			this.columnController.Add (this.columnBox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.columnController [this.columnBox]));
			w1.Position = 0;
			// Container child columnController.Gtk.Box+BoxChild
			this.minuxControl = new global::Gtk.VBox ();
			this.minuxControl.Name = "minuxControl";
			this.minuxControl.Spacing = 6;
			// Container child minuxControl.Gtk.Box+BoxChild
			this.labelEmpty1 = new global::Gtk.Label ();
			this.labelEmpty1.WidthRequest = 22;
			this.labelEmpty1.Name = "labelEmpty1";
			this.minuxControl.Add (this.labelEmpty1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.minuxControl [this.labelEmpty1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child minuxControl.Gtk.Box+BoxChild
			this.btnMinus = new global::Gtk.Button ();
			this.btnMinus.WidthRequest = 22;
			this.btnMinus.CanFocus = true;
			this.btnMinus.Name = "btnMinus";
			this.btnMinus.UseUnderline = true;
			this.btnMinus.Label = global::Mono.Unix.Catalog.GetString ("-");
			this.minuxControl.Add (this.btnMinus);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.minuxControl [this.btnMinus]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child minuxControl.Gtk.Box+BoxChild
			this.labelEmpty2 = new global::Gtk.Label ();
			this.labelEmpty2.WidthRequest = 22;
			this.labelEmpty2.Name = "labelEmpty2";
			this.minuxControl.Add (this.labelEmpty2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.minuxControl [this.labelEmpty2]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.columnController.Add (this.minuxControl);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.columnController [this.minuxControl]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child columnController.Gtk.Box+BoxChild
			this.plusControl = new global::Gtk.VBox ();
			this.plusControl.Name = "plusControl";
			this.plusControl.Spacing = 6;
			// Container child plusControl.Gtk.Box+BoxChild
			this.labelEmpty3 = new global::Gtk.Label ();
			this.labelEmpty3.WidthRequest = 22;
			this.labelEmpty3.Name = "labelEmpty3";
			this.plusControl.Add (this.labelEmpty3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.plusControl [this.labelEmpty3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child plusControl.Gtk.Box+BoxChild
			this.btnPlus = new global::Gtk.Button ();
			this.btnPlus.WidthRequest = 22;
			this.btnPlus.CanFocus = true;
			this.btnPlus.Name = "btnPlus";
			this.btnPlus.UseUnderline = true;
			this.btnPlus.Label = global::Mono.Unix.Catalog.GetString ("+");
			this.plusControl.Add (this.btnPlus);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.plusControl [this.btnPlus]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child plusControl.Gtk.Box+BoxChild
			this.labelEmpty4 = new global::Gtk.Label ();
			this.labelEmpty4.WidthRequest = 22;
			this.labelEmpty4.Name = "labelEmpty4";
			this.plusControl.Add (this.labelEmpty4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.plusControl [this.labelEmpty4]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.columnController.Add (this.plusControl);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.columnController [this.plusControl]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.columnController);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnMinus.Clicked += new global::System.EventHandler (this.OnBtnMinusClicked);
			this.btnPlus.Clicked += new global::System.EventHandler (this.OnBtnPlusClicked);
		}
	}
}
