
// This file has been generated by the GUI designer. Do not modify.
namespace RLToolkit.Widgets.Tests
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action mnuFile;
		private global::Gtk.Action mnuLoadConfig;
		private global::Gtk.Action mnuQuit;
		private global::Gtk.Action SelectTestAction;
		private global::Gtk.VBox vboxMain;
		private global::Gtk.MenuBar mnu;
		private global::Gtk.VBox voxInfo;
		private global::Gtk.Label lblInfo;
		private global::Gtk.HBox hBoxTestCount;
		private global::Gtk.Label lblInfo_TestCount;
		private global::Gtk.Label lblTestCount;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.VBox vboxWidget;
		private global::Gtk.HBox hboxButton;
		private global::Gtk.Button btnClick1;
		private global::Gtk.Button btnClick2;
		private global::Gtk.Button btnClick3;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.VBox vboxInfo2;
		private global::Gtk.HBox hBoxTestName;
		private global::Gtk.Label lblInfo_TestName;
		private global::Gtk.Label lblTestName;
		private global::Gtk.HBox hBoxTestDesc;
		private global::Gtk.Label lblInfo_TestDesc;
		private global::Gtk.Label lblTestDesc;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RLToolkit.Widgets.Tests.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.mnuFile = new global::Gtk.Action ("mnuFile", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.mnuFile.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.mnuFile, null);
			this.mnuLoadConfig = new global::Gtk.Action ("mnuLoadConfig", global::Mono.Unix.Catalog.GetString ("Load Configuration..."), null, null);
			this.mnuLoadConfig.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load Configuration...");
			w1.Add (this.mnuLoadConfig, null);
			this.mnuQuit = new global::Gtk.Action ("mnuQuit", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
			this.mnuQuit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.mnuQuit, null);
			this.SelectTestAction = new global::Gtk.Action ("SelectTestAction", global::Mono.Unix.Catalog.GetString ("Select Test..."), null, null);
			this.SelectTestAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select Test...");
			w1.Add (this.SelectTestAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "RLToolkit.Widgets.Tests.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child RLToolkit.Widgets.Tests.MainWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='mnu'><menu name='mnuFile' action='mnuFile'><menuitem name='SelectTestAction' action='SelectTestAction'/><menuitem name='mnuQuit' action='mnuQuit'/></menu></menubar></ui>");
			this.mnu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/mnu")));
			this.mnu.Name = "mnu";
			this.vboxMain.Add (this.mnu);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.mnu]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.voxInfo = new global::Gtk.VBox ();
			this.voxInfo.Name = "voxInfo";
			this.voxInfo.Spacing = 6;
			// Container child voxInfo.Gtk.Box+BoxChild
			this.lblInfo = new global::Gtk.Label ();
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Information:");
			this.voxInfo.Add (this.lblInfo);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.voxInfo [this.lblInfo]));
			w3.Position = 0;
			w3.Fill = false;
			// Container child voxInfo.Gtk.Box+BoxChild
			this.hBoxTestCount = new global::Gtk.HBox ();
			this.hBoxTestCount.Name = "hBoxTestCount";
			this.hBoxTestCount.Spacing = 6;
			// Container child hBoxTestCount.Gtk.Box+BoxChild
			this.lblInfo_TestCount = new global::Gtk.Label ();
			this.lblInfo_TestCount.Name = "lblInfo_TestCount";
			this.lblInfo_TestCount.LabelProp = global::Mono.Unix.Catalog.GetString ("Test Count:");
			this.hBoxTestCount.Add (this.lblInfo_TestCount);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hBoxTestCount [this.lblInfo_TestCount]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hBoxTestCount.Gtk.Box+BoxChild
			this.lblTestCount = new global::Gtk.Label ();
			this.lblTestCount.Name = "lblTestCount";
			this.hBoxTestCount.Add (this.lblTestCount);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hBoxTestCount [this.lblTestCount]));
			w5.Position = 1;
			this.voxInfo.Add (this.hBoxTestCount);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.voxInfo [this.hBoxTestCount]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vboxMain.Add (this.voxInfo);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.voxInfo]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vboxMain.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hseparator1]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.vboxWidget = new global::Gtk.VBox ();
			this.vboxWidget.Name = "vboxWidget";
			this.vboxWidget.Spacing = 6;
			this.vboxMain.Add (this.vboxWidget);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.vboxWidget]));
			w9.Position = 3;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxButton = new global::Gtk.HBox ();
			this.hboxButton.Name = "hboxButton";
			this.hboxButton.Homogeneous = true;
			this.hboxButton.Spacing = 6;
			// Container child hboxButton.Gtk.Box+BoxChild
			this.btnClick1 = new global::Gtk.Button ();
			this.btnClick1.CanFocus = true;
			this.btnClick1.Name = "btnClick1";
			this.btnClick1.UseUnderline = true;
			this.btnClick1.Label = global::Mono.Unix.Catalog.GetString ("Control 1");
			this.hboxButton.Add (this.btnClick1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxButton [this.btnClick1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hboxButton.Gtk.Box+BoxChild
			this.btnClick2 = new global::Gtk.Button ();
			this.btnClick2.CanFocus = true;
			this.btnClick2.Name = "btnClick2";
			this.btnClick2.UseUnderline = true;
			this.btnClick2.Label = global::Mono.Unix.Catalog.GetString ("Control 2");
			this.hboxButton.Add (this.btnClick2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxButton [this.btnClick2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hboxButton.Gtk.Box+BoxChild
			this.btnClick3 = new global::Gtk.Button ();
			this.btnClick3.CanFocus = true;
			this.btnClick3.Name = "btnClick3";
			this.btnClick3.UseUnderline = true;
			this.btnClick3.Label = global::Mono.Unix.Catalog.GetString ("Control 3");
			this.hboxButton.Add (this.btnClick3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxButton [this.btnClick3]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.vboxMain.Add (this.hboxButton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxButton]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vboxMain.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hseparator2]));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.vboxInfo2 = new global::Gtk.VBox ();
			this.vboxInfo2.Name = "vboxInfo2";
			this.vboxInfo2.Spacing = 6;
			// Container child vboxInfo2.Gtk.Box+BoxChild
			this.hBoxTestName = new global::Gtk.HBox ();
			this.hBoxTestName.Name = "hBoxTestName";
			this.hBoxTestName.Spacing = 6;
			// Container child hBoxTestName.Gtk.Box+BoxChild
			this.lblInfo_TestName = new global::Gtk.Label ();
			this.lblInfo_TestName.Name = "lblInfo_TestName";
			this.lblInfo_TestName.LabelProp = global::Mono.Unix.Catalog.GetString ("Test Name:");
			this.hBoxTestName.Add (this.lblInfo_TestName);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hBoxTestName [this.lblInfo_TestName]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hBoxTestName.Gtk.Box+BoxChild
			this.lblTestName = new global::Gtk.Label ();
			this.lblTestName.Name = "lblTestName";
			this.hBoxTestName.Add (this.lblTestName);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hBoxTestName [this.lblTestName]));
			w16.Position = 1;
			this.vboxInfo2.Add (this.hBoxTestName);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxInfo2 [this.hBoxTestName]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vboxInfo2.Gtk.Box+BoxChild
			this.hBoxTestDesc = new global::Gtk.HBox ();
			this.hBoxTestDesc.Name = "hBoxTestDesc";
			this.hBoxTestDesc.Spacing = 6;
			// Container child hBoxTestDesc.Gtk.Box+BoxChild
			this.lblInfo_TestDesc = new global::Gtk.Label ();
			this.lblInfo_TestDesc.Name = "lblInfo_TestDesc";
			this.lblInfo_TestDesc.LabelProp = global::Mono.Unix.Catalog.GetString ("Test Description:");
			this.hBoxTestDesc.Add (this.lblInfo_TestDesc);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hBoxTestDesc [this.lblInfo_TestDesc]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hBoxTestDesc.Gtk.Box+BoxChild
			this.lblTestDesc = new global::Gtk.Label ();
			this.lblTestDesc.HeightRequest = 40;
			this.lblTestDesc.Name = "lblTestDesc";
			this.hBoxTestDesc.Add (this.lblTestDesc);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hBoxTestDesc [this.lblTestDesc]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 1;
			this.vboxInfo2.Add (this.hBoxTestDesc);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxInfo2 [this.hBoxTestDesc]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.vboxMain.Add (this.vboxInfo2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.vboxInfo2]));
			w21.Position = 6;
			w21.Expand = false;
			w21.Fill = false;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 589;
			this.DefaultHeight = 555;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.mnuQuit.Activated += new global::System.EventHandler (this.OnMnuQuitActivated);
			this.SelectTestAction.Activated += new global::System.EventHandler (this.OnSelectTestActionActivated);
		}
	}
}
